package com.ssm.base.user.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uage
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    private String uage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usex
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    private String usex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uage
     *
     * @return the value of user.uage
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public String getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uage
     *
     * @param uage the value for user.uage
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public void setUage(String uage) {
        this.uage = uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usex
     *
     * @return the value of user.usex
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public String getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usex
     *
     * @param usex the value for user.usex
     *
     * @mbg.generated Thu Aug 23 09:54:55 CST 2018
     */
    public void setUsex(String usex) {
        this.usex = usex;
    }
}